# Generated by Django 3.1.3 on 2020-11-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewCases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caserecord',
            name='dateOfConfirm',
            field=models.DateField(verbose_name='Date Confirmed'),
        ),
        migrations.AlterField(
            model_name='caserecord',
            name='localOrImported',
            field=models.CharField(max_length=20, verbose_name='Local or Imported'),
        ),
    ]
